# NumPy for Pandas

Installing and Importing NumPy

In [1]:
import numpy as np

Benefits and Characterstics of NumPy arrays

In [ ]:
def squares(values):
    result = []
    for v in values:
        result.append(v*v)
    return result

toSquare = range(100000)
%timeit squares(toSquare)

In [ ]:
arrayToSquare = np.arange(0, 100000)
%timeit arrayToSquare**2

Creating NumPy arrays and performing
basic array operations

In [5]:
a1 = np.array([1, 2, 3, 4, 5])

In [6]:
a1

array([1, 2, 3, 4, 5])

In [14]:
type(a1)

numpy.ndarray

In [16]:
a1.dtype

dtype('int32')

In [9]:
np.size(a1)

5

In [11]:
a2 = np.array([1, 2, 3.0, 4.5])

In [12]:
a2

array([1. , 2. , 3. , 4.5])

In [13]:
type(a2)

numpy.ndarray

In [17]:
a2.dtype

dtype('float64')

In [18]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [26]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
a2 = np.arange(10,20)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
a1 + a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [36]:
m = np.arange(0,20).reshape(5,4)

In [37]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
np.size(m)

20

In [39]:
m.dtype

dtype('int32')

In [40]:
len(m)

5

In [43]:
np.size(m,0) #Num of rows

5

In [44]:
np.size(m, 1) #Num of columns

4

Selecting array elements

In [45]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1[0]

0

In [48]:
a1[2]

2

In [49]:
a1[0], a1[2]

(0, 2)

In [50]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
m[1, 2]

6

In [52]:
m[1,]

array([4, 5, 6, 7])

In [55]:
m[:,2]

array([ 2,  6, 10, 14, 18])

Logical operations on arrays

In [57]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [60]:
(a < 2)

array([ True,  True, False, False, False])

In [61]:
(a < 2).dtype

dtype('bool')

In [62]:
(a < 2) | (a > 3)

array([ True,  True, False, False,  True])

In [63]:
def exp(x):
    return x<3 or x>3

In [64]:
a

array([0, 1, 2, 3, 4])

In [65]:
np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [67]:
r = a<3
r

array([ True,  True,  True, False, False])

In [69]:
a[r]

array([0, 1, 2])

In [70]:
np.sum(a)

10

In [71]:
a

array([0, 1, 2, 3, 4])

In [74]:
np.sum(a<3)

3

In [75]:
a1 = np.arange(0, 5)
a1

array([0, 1, 2, 3, 4])

In [2]:
a2 = np.arange(5, 0, -1)
a2

NameError: name 'np' is not defined

In [3]:
a1 < a2

NameError: name 'a1' is not defined

In [83]:
a1 = np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
a2 = np.arange(9, 0, -1).reshape(3,3)
a2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [85]:
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

Slicing Arrays

In [1]:
a1 = np.arange(1, 10)
a1[3:8]

NameError: name 'np' is not defined